#
# _                                     _____ _____
# | |                              /\   |  __ \_   _|
# | |     __ _ _ __   __ _ ______ /  \  | |__) || |
# | |    / _` | '_ \ / _` |______/ /\ \ |  ___/ | |
# | |___| (_| | | | | (_| |     / ____ \| |    _| |_
# |______\__,_|_| |_|\__, |    /_/    \_\_|   |_____|
#                     __/ |
#                    |___/

#MySQL credentials
#url-example: jdbc:mysql://host:port/database
mysql.url:
mysql.user:
mysql.password:






